/**
* This file is generated by 'protoapi'
* This file contains all the data structure being used in the generated ts services
* -----------------------------------------------------
* 该文件生成于protoapi
* 文件包含API前端调用所引用的数据结构定义
*/

// enums
export enum ValidateErrorType {
    INVALID_EMAIL = 0,
    FIELD_REQUIRED = 1,
}

export enum ErrorCode {
    DefaultError = 0,
    GeneralError = 1000,
    DatabaseError = 1001,
    EtcdError = 1002,
    SystemError = 1003,
}
// data types
export interface CommonError {
    
    genericError: GenericError
    authError: AuthError
    validateError: ValidateError
    bindError: BindError
}

export interface GenericError {
    
    kind: "genericError"
    
    message: string
}

export interface AuthError {
    
    kind: "authError"
    
    message: string
}

export interface BindError {
    
    kind: "bindError"
    
    message: string
}

export interface ValidateError {
    
    kind: "validateError"
    
    errors: FieldError[]
}

export interface FieldError {
    
    fieldName: string
    errorType: ValidateErrorType
}

export interface Empty {
    
}

export interface Error {
    
    kind: "error"
    
    error_code: ErrorCode
    message: string
}

export interface MiniProgramLoginReq {
    
    jscode: string
}

export interface MiniProgramLoginResp {
    
    user_status: number
    token: string
}

export interface MiniProgramRegisterReq {
    
    jscode: string
    invitation_code: string
}

export interface MiniProgramRegisterResp {
    
    token: string
}
